### ISSUE TITLE
using other mqtt settings

### ISSUE THREAD

**Issue by martinw72** [harb70/bayrolas5-nodered#1]
I#m sing EspPresence and some MQTT-Sensors (MQTTOpenGateway). Is it still possible to use your workflow?

**Comment by harb70** [comment]
i suppose so, in NodeRed it's a MQTT client node connected to Bayrol broker, the second node is connected to Mosquitto, but can be MQTT broker you use at home and read by Home Assistant MQTT integration, or things similar in Jeedom.
You need to replace the mosquitto Broker configuration in the flow by the MQTTOpengateway config. (as HA can only have 1 broker configured in the integration)

**Comment by martinw72** [comment]
Thanks a lot. Will give it a try!
